# AKS Values for kube-prometheus-stack + Loki

loki:
  enabled: true
  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h

prometheus:
  prometheusSpec:
    retention: 6h
    serviceMonitorSelectorNilUsesHelmValues: false