# AKS Values for kube-prometheus-stack + Loki

loki:
  enabled: true
  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h

grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard

prometheus:
  prometheusSpec:
    retention: 6h
    serviceMonitorSelectorNilUsesHelmValues: false