init:
	terraform init

plan:
	terraform plan

apply:
	terraform apply -auto-approve

destroy:
	terraform destroy -auto-approve

fmt:
	terraform fmt -recursive

lint:
	tflint

sec:
	tfsec .

docs:
	terraform-docs . > README.md