param location string = resourceGroup().location
param grafanaName string = 'nick-grafana'

resource grafana 'Microsoft.Dashboard/grafana@2022-08-01' = {
  name: grafanaName
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    publicNetworkAccess: 'Enabled'
    apiKey: {
      enabled: true
    }
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    deterministicOutboundIP: 'Enabled'
  }
  sku: {
    name: 'Standard'
  }
}

output grafanaEndpoint string = 'https://${grafana.name}.grafana.azure.com'
output grafanaName string = grafana.name
