@description('Grafana workspace name')
param grafanaName string

@description('Location of Grafana')
param location string

@description('Resource group name')
param resourceGroupName string

@description('Environment')
param environment string

@description('Log Analytics workspace resource ID')
param workspaceResourceId string

resource grafana 'Microsoft.Dashboard/grafana@2023-09-01' = {
  name: grafanaName
  location: location
  identity: {
    type: 'SystemAssigned'
  } 
  sku: {
    name: 'Standard'
  }
  properties: {
    publicNetworkAccess: 'Enabled'
    zoneRedundancy: 'Disabled'
    apiKey: 'Disabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
  }
}

output grafanaEndpoint string = grafana.properties.endpoint