apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-log-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-log-demo
  template:
    metadata:
      labels:
        app: node-log-demo
      annotations:
        promtail.io/scrape: "true"
    spec:
      containers:
        - name: node
          image: ghcr.io/nickthedevopsguy/node-log-demo:latest
          ports:
            - containerPort: 3000