name: CI Pipeline

on:
  push:
    paths:
      - 'ci-cd-github-actions/**'
    branches: [ "develop" ]
  pull_request:
    paths:
      - 'ci-cd-github-actions/**'
    branches: [ "develop" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: ⬇️ Checkout code
      uses: actions/checkout@v3

    - name: ⚙️ Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: 📦 Install dependencies
      run: npm install

    - name: 🧹 Run ESLint
      run: npx eslint .

    - name: 🧪 Run Jest tests
      run: npm test

    - name: 📊 Generate coverage report
      run: npx jest --coverage --ci

    - name: 💾 Upload coverage artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/

    - name: 🐳 Log in to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u "${{ secrets.CR_USERNAME }}" --password-stdin

    - name: 🏗️ Build Docker image
      run: |
        IMAGE_ID=ghcr.io/${{ secrets.CR_USERNAME }}/node-ci-app
        IMAGE_TAG=latest
        docker build -t $IMAGE_ID:$IMAGE_TAG .

    - name: 🚀 Push Docker image
      run: |
        IMAGE_ID=ghcr.io/${{ secrets.CR_USERNAME }}/node-ci-app
        IMAGE_TAG=latest
        docker push $IMAGE_ID:$IMAGE_TAG
